# ***********************************************
# Example Configuration (example.yaml)
# Demonstrates supported fields, meanings, default values,
# and applicability across the four protocols (UDP / TCP / TLS / HTTPS).
# ***********************************************

listen_addresses:
  # List of local addresses the DNS service will listen on.
  # Optional. Default: ["0.0.0.0:53", "[::]:53"]
  - "0.0.0.0:53"
  - "[::]:53"

dns_servers:
  # --------------------------
  # 1) UDP mode (default)
  # --------------------------
  - address: "8.8.8.8:53"
    # Remote DNS server address. IPv4 and IPv6 supported.
    # Required.
    
    protocol: "UDP"
    # Protocol type. Supported values: UDP / TCP / TLS / HTTPS
    # Optional. Default: UDP

    filters:
      # A list of domain filters. Only domain names matching these filters will be forwarded to this DNS server.
      # Two filter formats are supported:
      #   1. Exact domain match (e.g., "www.example.com")
      #   2. Subdomain wildcard match (e.g., "*.example.org")
      #
      # Notes:
      # - A wildcard filter like "*.example.org" matches subdomains such as "foo.example.org" but does NOT match "example.org" itself.
      # - To include both the base domain and its subdomains, specify both "example.org" and "*.example.org" explicitly.
      #
      # Optional. If omitted, all domain queries ("*") are forwarded to this DNS server.
      - "www.example.com"
      - "*.example.org"
      # Filters can also be loaded from an external file. The path can be relative or absolute.
      # If the path starts with '@', the program will attempt to load filters from the specified file.
      # The file should contain one filter per line.
      # Filters written in a file should not contain '@' as loading files recursively is not allowed.
      # Example:
      #   @config/example-filters.txt
      #   @/path/to/this/program/config/example-filters.txt
      - "@config/example-filters.txt"

    timeout: 2000
    # Request timeout in milliseconds.
    # Optional. Default: 2000

    max_retry: 2
    # Maximum number of retries after failure.
    # Optional. Default: 2

    proxy_type: "NONE"
    # Proxy type for DNS queries. Supported values: NONE / SOCKS5 / HTTP
    # Optional. Default: NONE

    # proxy_address: "127.0.0.1:1080"
    # Proxy server address.
    # Required if proxy_type ≠ NONE.

  # --------------------------
  # 2) TCP mode
  # --------------------------
  - address: "8.8.4.4:53"
    protocol: "TCP"

    filters:
      # Domain filters for this DNS server. See 'filters' in UDP mode above for details.
      # Optional. Default: "*"
      - "www.example.com"
      - "*.example.org"
      - "@config/example-filters.txt"

    timeout: 2000
    # Request timeout in milliseconds.
    # Optional. Default: 2000

    max_retry: 2
    # Maximum number of retries.
    # Optional. Default: 2

    reuse_tcp_connection: false
    # Whether to reuse TCP connections.
    # Optional. Default: false in TCP mode (most DNS servers do not allow reuse).

    proxy_type: "HTTP"
    # Proxy type for DNS queries.
    # Optional. Default: NONE

    proxy_address: "127.0.0.1:1080"
    # Proxy server address.
    # Required if proxy_type ≠ NONE.

  # --------------------------
  # 3) TLS mode (DoT - DNS over TLS)
  # --------------------------
  - address: "[2001:4860:4860::8888]:853"
    protocol: "TLS"

    hostname: "dns.google"
    # Remote server hostname.
    # Required.

    verify_cert: true
    # Whether to verify the remote server's certificate.
    # Optional. Default: true

    filters:
      # Domain filters for this DNS server. See 'filters' in UDP mode above for details.
      # Optional. Default: "*"
      - "www.example.com"
      - "*.example.org"
      - "@config/example-filters.txt"

    timeout: 2000
    # Request timeout in milliseconds.
    # Optional. Default: 2000

    max_retry: 2
    # Maximum number of retries.
    # Optional. Default: 2

    reuse_tcp_connection: true
    # Whether to reuse TCP connections.
    # Optional. Default: true in TLS mode (reuse is typically supported).

    proxy_type: "SOCKS5"
    # Proxy type for DNS queries.
    # Optional. Default: NONE

    proxy_address: "127.0.0.1:1080"
    # Proxy server address.
    # Required if proxy_type ≠ NONE.

  # --------------------------
  # 4) HTTPS mode (DoH - DNS over HTTPS)
  # --------------------------
  - address: "[2001:4860:4860::8844]:443"
    protocol: "HTTPS"

    hostname: "dns.google"
    # Remote server hostname.
    # Required.

    doh_path: "dns-query"
    # DoH request path, typically "dns-query". The URL actually used would be "https://{hostname}/{doh_path}".
    # Required.

    verify_cert: true
    # Whether to verify the remote server's certificate.
    # Optional. Default: true

    filters:
      # Domain filters for this DNS server. See 'filters' in UDP mode above for details.
      # Optional. Default: "*"
      - "www.example.com"
      - "*.example.org"
      - "@config/example-filters.txt"

    timeout: 2000
    # Request timeout in milliseconds.
    # Optional. Default: 2000

    max_retry: 2
    # Maximum number of retries.
    # Optional. Default: 2

    proxy_type: "SOCKS5"
    # Proxy type.
    # Optional. Default: NONE

    proxy_address: "127.0.0.1:1080"
    # Proxy server address.
    # Required if proxy_type ≠ NONE.
